"""SQLAlchemy models for O-Brain Coach intelligence engine."""

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base, TimestampMixin


class MeetingIntelligence(TimestampMixin, Base):
    """AI-generated intelligence from a meeting transcript."""

    __tablename__ = "meeting_intelligence"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    meeting_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("meetings.id", ondelete="CASCADE"), nullable=False, unique=True, index=True
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    summary_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    topics_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    action_items_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    decisions_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    sentiment_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    talk_ratio_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    deal_signals_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    risk_flags_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    follow_ups_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    suggestions_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    action_items_completed_json: Mapped[str | None] = mapped_column(Text, nullable=True)


class MonthlyReport(TimestampMixin, Base):
    """Monthly intelligence report generated by O-Brain Coach."""

    __tablename__ = "monthly_reports"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    report_month: Mapped[str] = mapped_column(String(7), nullable=False)  # YYYY-MM
    executive_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    whats_working_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    watch_out_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    revenue_insights_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    meeting_patterns_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    recommendations_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    trend_data_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    win_loss_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    health_score: Mapped[int] = mapped_column(Integer, default=50, server_default="50")
    raw_data_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    team_data_json: Mapped[str | None] = mapped_column(Text, nullable=True)


class DealOutcome(TimestampMixin, Base):
    """Win/loss tracking linked to proposals and contacts."""

    __tablename__ = "deal_outcomes"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    contact_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("contacts.id", ondelete="SET NULL"), nullable=True
    )
    proposal_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("proposals.id", ondelete="SET NULL"), nullable=True
    )
    outcome: Mapped[str] = mapped_column(String(20), nullable=False)  # win / loss / pending
    deal_value: Mapped[float] = mapped_column(Float, default=0, server_default="0")
    cycle_days: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    meetings_count: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    emails_count: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    win_factors_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    loss_factors_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    analysis_json: Mapped[str | None] = mapped_column(Text, nullable=True)


class CoachingNudge(TimestampMixin, Base):
    """Proactive coaching nudges sent to users."""

    __tablename__ = "coaching_nudges"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    nudge_type: Mapped[str] = mapped_column(String(50), nullable=False)
    # Types: meeting_followup, proposal_followup, overdue_invoice, weekly_digest, deal_insight
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    context_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_read: Mapped[bool] = mapped_column(Boolean, default=False, server_default="0")
    is_acted_on: Mapped[bool] = mapped_column(Boolean, default=False, server_default="0")
