"""add phase2 contact_tags activities file_shares portal invitations roles

Revision ID: 11af39e2af84
Revises: 3c2792534b88
Create Date: 2026-03-06 10:58:58.972558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11af39e2af84'
down_revision: Union[str, None] = '3c2792534b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_portal_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_portal_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_portal_accounts_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('contact_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('activity_type', sa.Enum('EMAIL_SENT', 'EMAIL_RECEIVED', 'SMS_SENT', 'SMS_RECEIVED', 'INVOICE_SENT', 'INVOICE_PAID', 'PROPOSAL_SENT', 'PROPOSAL_SIGNED', 'PAYMENT_RECEIVED', 'FILE_SHARED', 'MEETING_SCHEDULED', 'MEETING_COMPLETED', 'NOTE_ADDED', 'CALL_LOGGED', name='activitytype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_activities_contact_id'), ['contact_id'], unique=False)

    op.create_table('contact_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_tags_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_tags_tag_name'), ['tag_name'], unique=False)

    op.create_table('user_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', name='invitationstatus'), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('user_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_invitations_email'), ['email'], unique=False)

    op.create_table('file_shares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.Enum('VIEW', 'DOWNLOAD', name='filesharepermission'), nullable=False),
    sa.Column('shared_by', sa.Uuid(), nullable=False),
    sa.Column('shared_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_shares_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_shares_file_id'), ['file_id'], unique=False)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contacts_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_foreign_key('fk_contacts_assigned_user', 'users', ['assigned_user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('ADMIN', 'TEAM_MEMBER', 'ACCOUNTANT', 'CLIENT', 'VIEWER', name='role'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'TEAM_MEMBER', 'ACCOUNTANT', 'CLIENT', 'VIEWER', name='role'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contacts_assigned_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contacts_assigned_user_id'))
        batch_op.drop_column('assigned_user_id')

    with op.batch_alter_table('file_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_shares_file_id'))
        batch_op.drop_index(batch_op.f('ix_file_shares_contact_id'))

    op.drop_table('file_shares')
    with op.batch_alter_table('user_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_invitations_email'))

    op.drop_table('user_invitations')
    with op.batch_alter_table('contact_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_tags_tag_name'))
        batch_op.drop_index(batch_op.f('ix_contact_tags_contact_id'))

    op.drop_table('contact_tags')
    with op.batch_alter_table('contact_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_activities_contact_id'))

    op.drop_table('contact_activities')
    with op.batch_alter_table('client_portal_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_portal_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_accounts_contact_id'))

    op.drop_table('client_portal_accounts')
    # ### end Alembic commands ###
