"""add reconciliation and unified_messages tables

Revision ID: 3c2792534b88
Revises: 603b125685d3
Create Date: 2026-03-06 07:34:22.695924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2792534b88'
down_revision: Union[str, None] = '603b125685d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_event', sa.String(length=50), nullable=False),
    sa.Column('delay_hours', sa.Integer(), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('send_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_up_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_up_rules_resource_id'), ['resource_id'], unique=False)

    op.create_table('ghl_sync_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('ghl_entity_id', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.Enum('PUSH', 'PULL', name='syncdirection'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', name='syncstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ghl_sync_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ghl_sync_log_entity_id'), ['entity_id'], unique=False)

    op.create_table('proposal_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_number', sa.String(length=20), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'VIEWED', 'WAITING_SIGNATURE', 'SIGNED', 'DECLINED', 'PAID', name='proposalstatus'), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('collect_payment', sa.Boolean(), nullable=False),
    sa.Column('payment_mode', sa.String(length=20), nullable=True),
    sa.Column('payment_frequency', sa.String(length=20), nullable=True),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PROCESSING', 'PAID', name='paymentstatus'), nullable=True),
    sa.Column('public_token', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_enabled', sa.Boolean(), nullable=False),
    sa.Column('follow_up_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['proposal_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_number')
    )
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposals_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposals_public_token'), ['public_token'], unique=True)

    op.create_table('unified_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('message_type', sa.Enum('EMAIL', 'SMS', name='messagetype'), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='messagedirection'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unified_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unified_messages_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unified_messages_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_unified_messages_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unified_messages_user_id'), ['user_id'], unique=False)

    op.create_table('proposal_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposal_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_activities_proposal_id'), ['proposal_id'], unique=False)

    op.create_table('proposal_recipients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('signing_order', sa.Integer(), nullable=False),
    sa.Column('signing_token', sa.String(length=64), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('signature_type', sa.String(length=20), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposal_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_recipients_proposal_id'), ['proposal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_recipients_signing_token'), ['signing_token'], unique=True)

    op.create_table('receipt_transaction_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('match_reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', name='matchstatus'), nullable=False),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receipt_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['cashbook_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipt_transaction_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_transaction_matches_receipt_id'), ['receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_transaction_matches_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_transaction_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_transaction_matches_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_receipt_transaction_matches_receipt_id'))

    op.drop_table('receipt_transaction_matches')
    with op.batch_alter_table('proposal_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_recipients_signing_token'))
        batch_op.drop_index(batch_op.f('ix_proposal_recipients_proposal_id'))

    op.drop_table('proposal_recipients')
    with op.batch_alter_table('proposal_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_activities_proposal_id'))

    op.drop_table('proposal_activities')
    with op.batch_alter_table('unified_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unified_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_unified_messages_thread_id'))
        batch_op.drop_index(batch_op.f('ix_unified_messages_message_type'))
        batch_op.drop_index(batch_op.f('ix_unified_messages_contact_id'))

    op.drop_table('unified_messages')
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposals_public_token'))
        batch_op.drop_index(batch_op.f('ix_proposals_contact_id'))

    op.drop_table('proposals')
    op.drop_table('proposal_templates')
    with op.batch_alter_table('ghl_sync_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ghl_sync_log_entity_id'))

    op.drop_table('ghl_sync_log')
    with op.batch_alter_table('follow_up_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_up_rules_resource_id'))

    op.drop_table('follow_up_rules')
    # ### end Alembic commands ###
