"""add brain tables

Revision ID: 4b2377d12eeb
Revises: a7194612ee9e
Create Date: 2026-03-06 18:12:48.077137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2377d12eeb'
down_revision: Union[str, None] = 'a7194612ee9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brain_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.Enum('EXPENSE_CATEGORIZATION', 'RECEIPT_IMPORT', 'MEETING_SUMMARY', 'FINANCIAL_COMMITMENT_DETECTION', 'WORKFLOW_AI_ACTION', 'PROACTIVE_ALERT', 'CHAT_QUERY', name='auditactiontype'), nullable=False),
    sa.Column('ai_input', sa.Text(), nullable=True),
    sa.Column('ai_output', sa.Text(), nullable=True),
    sa.Column('human_decision', sa.String(length=50), nullable=True),
    sa.Column('source_data_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_bal_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brain_audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_bal_user_action', ['user_id', 'action_type'], unique=False)

    op.create_table('brain_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_brain_conv_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brain_conversations', schema=None) as batch_op:
        batch_op.create_index('ix_brain_conv_user', ['user_id'], unique=False)

    op.create_table('proactive_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.Enum('OVERDUE_INVOICE', 'UNSIGNED_PROPOSAL', 'TAX_DEADLINE', 'EXPENSE_ANOMALY', 'REVENUE_MILESTONE', 'STALE_CONTACTS', 'UNRESPONDED_MESSAGES', 'UPCOMING_RENEWAL', 'UNACTIONED_COMMITMENT', 'FINANCIAL_COMMITMENT', name='alerttype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_pa_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proactive_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_pa_user_read', ['user_id', 'is_read'], unique=False)

    op.create_table('transcription_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('recording_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'DEAD_LETTER', name='transcriptionstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_tq_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcription_queue', schema=None) as batch_op:
        batch_op.create_index('ix_tq_status', ['status'], unique=False)
        batch_op.create_index('ix_tq_user', ['user_id'], unique=False)

    op.create_table('brain_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('EMAIL', 'SMS', 'CALL_TRANSCRIPT', 'MEETING_TRANSCRIPT', 'CALL_NOTES', 'MEETING_NOTES', 'DOCUMENT', 'BRAND_KNOWLEDGE', 'MANUAL_NOTE', 'FORM_RESPONSE', 'INTERNAL_COMMENT', name='embeddingsourcetype'), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('relevance_weight', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='fk_brain_emb_contact', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_brain_emb_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brain_embeddings', schema=None) as batch_op:
        batch_op.create_index('ix_brain_emb_contact', ['contact_id'], unique=False)
        batch_op.create_index('ix_brain_emb_source_id', ['source_id'], unique=False)
        batch_op.create_index('ix_brain_emb_user_source', ['user_id', 'source_type'], unique=False)

    op.create_table('brain_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tools_used_json', sa.Text(), nullable=True),
    sa.Column('sources_cited_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['brain_conversations.id'], name='fk_brain_msg_conv', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brain_messages', schema=None) as batch_op:
        batch_op.create_index('ix_brain_msg_conv', ['conversation_id'], unique=False)

    op.create_table('call_transcripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_sid', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('speakers_json', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_items_json', sa.Text(), nullable=True),
    sa.Column('financial_commitments_json', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='fk_ct_contact', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_ct_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_transcripts', schema=None) as batch_op:
        batch_op.create_index('ix_ct_contact', ['contact_id'], unique=False)
        batch_op.create_index('ix_ct_user', ['user_id'], unique=False)

    op.create_table('meeting_transcripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('speakers_json', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_items_json', sa.Text(), nullable=True),
    sa.Column('financial_commitments_json', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name='fk_mt_meeting', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_mt_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_transcripts', schema=None) as batch_op:
        batch_op.create_index('ix_mt_meeting', ['meeting_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_transcripts', schema=None) as batch_op:
        batch_op.drop_index('ix_mt_meeting')

    op.drop_table('meeting_transcripts')
    with op.batch_alter_table('call_transcripts', schema=None) as batch_op:
        batch_op.drop_index('ix_ct_user')
        batch_op.drop_index('ix_ct_contact')

    op.drop_table('call_transcripts')
    with op.batch_alter_table('brain_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_brain_msg_conv')

    op.drop_table('brain_messages')
    with op.batch_alter_table('brain_embeddings', schema=None) as batch_op:
        batch_op.drop_index('ix_brain_emb_user_source')
        batch_op.drop_index('ix_brain_emb_source_id')
        batch_op.drop_index('ix_brain_emb_contact')

    op.drop_table('brain_embeddings')
    with op.batch_alter_table('transcription_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_tq_user')
        batch_op.drop_index('ix_tq_status')

    op.drop_table('transcription_queue')
    with op.batch_alter_table('proactive_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_pa_user_read')

    op.drop_table('proactive_alerts')
    with op.batch_alter_table('brain_conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_brain_conv_user')

    op.drop_table('brain_conversations')
    with op.batch_alter_table('brain_audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_bal_user_action')

    op.drop_table('brain_audit_log')
    # ### end Alembic commands ###
