"""add phase4 pages scheduling branding tables

Revision ID: a7194612ee9e
Revises: eef17b52e8a1
Create Date: 2026-03-06 13:30:43.215413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7194612ee9e'
down_revision: Union[str, None] = 'eef17b52e8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branding_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('logo_dark_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=20), server_default='#2563eb', nullable=False),
    sa.Column('secondary_color', sa.String(length=20), server_default='#64748b', nullable=False),
    sa.Column('accent_color', sa.String(length=20), server_default='#f59e0b', nullable=False),
    sa.Column('font_heading', sa.String(length=100), server_default='Inter', nullable=False),
    sa.Column('font_body', sa.String(length=100), server_default='Inter', nullable=False),
    sa.Column('border_radius', sa.String(length=20), server_default='8px', nullable=False),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('email_header_html', sa.Text(), nullable=True),
    sa.Column('email_footer_html', sa.Text(), nullable=True),
    sa.Column('portal_welcome_message', sa.Text(), nullable=True),
    sa.Column('booking_page_header', sa.Text(), nullable=True),
    sa.Column('org_slug', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_branding_updated_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_slug')
    )
    op.create_table('pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='pagestatus'), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('css_content', sa.Text(), nullable=True),
    sa.Column('js_content', sa.Text(), nullable=True),
    sa.Column('sections_json', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('og_image_url', sa.String(length=500), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('is_homepage', sa.Boolean(), nullable=False),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('custom_head_html', sa.Text(), nullable=True),
    sa.Column('style_preset', sa.String(length=50), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('font_family', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_slug'), ['slug'], unique=False)

    op.create_table('scheduling_calendars',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('calendar_type', sa.Enum('PERSONAL', 'TEAM', 'ROUND_ROBIN', name='calendartype'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('max_advance_days', sa.Integer(), nullable=False),
    sa.Column('min_notice_hours', sa.Integer(), nullable=False),
    sa.Column('availability_json', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('confirmation_message', sa.Text(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('google_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduling_calendars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduling_calendars_slug'), ['slug'], unique=False)

    op.create_table('calendar_bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('calendar_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_user_id', sa.Uuid(), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=False),
    sa.Column('guest_phone', sa.String(length=50), nullable=True),
    sa.Column('guest_notes', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', name='bookingstatus'), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('reminder_24h_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_1h_sent', sa.Boolean(), nullable=False),
    sa.Column('confirmation_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name='fk_calendar_bookings_assigned_user', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['calendar_id'], ['scheduling_calendars.id'], name='fk_calendar_bookings_calendar', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='fk_calendar_bookings_contact', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_bookings_calendar_id'), ['calendar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_bookings_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_bookings_guest_email'), ['guest_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_bookings_start_time'), ['start_time'], unique=False)

    op.create_table('calendar_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('calendar_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['scheduling_calendars.id'], name='fk_calendar_members_calendar', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_calendar_members_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_members_calendar_id'), ['calendar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_members_user_id'), ['user_id'], unique=False)

    op.create_table('page_analytics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('visitor_ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name='fk_page_analytics_page', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_analytics_page_id'), ['page_id'], unique=False)

    op.create_table('page_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('css_content', sa.Text(), nullable=True),
    sa.Column('js_content', sa.Text(), nullable=True),
    sa.Column('sections_json', sa.Text(), nullable=True),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name='fk_page_versions_page', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_versions_page_id'), ['page_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_versions_page_id'))

    op.drop_table('page_versions')
    with op.batch_alter_table('page_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_analytics_page_id'))

    op.drop_table('page_analytics')
    with op.batch_alter_table('calendar_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_members_calendar_id'))

    op.drop_table('calendar_members')
    with op.batch_alter_table('calendar_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_bookings_start_time'))
        batch_op.drop_index(batch_op.f('ix_calendar_bookings_guest_email'))
        batch_op.drop_index(batch_op.f('ix_calendar_bookings_contact_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_bookings_calendar_id'))

    op.drop_table('calendar_bookings')
    with op.batch_alter_table('scheduling_calendars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduling_calendars_slug'))

    op.drop_table('scheduling_calendars')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_slug'))

    op.drop_table('pages')
    op.drop_table('branding_settings')
    # ### end Alembic commands ###
