"""Add brain_chat_files, smart_imports, smart_import_items, kyc_verifications tables

Revision ID: ab286478fc11
Revises: 4b2377d12eeb
Create Date: 2026-03-06 23:26:02.913939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab286478fc11'
down_revision: Union[str, None] = '4b2377d12eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brain_chat_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['brain_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('smart_imports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False, server_default='pending'),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('smart_import_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False, server_default='pending'),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('category_suggestion', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False, server_default='0.0'),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False, server_default='0'),
    sa.Column('duplicate_entry_id', sa.Uuid(), nullable=True),
    sa.Column('cashbook_entry_id', sa.Uuid(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['smart_imports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cashbook_entry_id'], ['cashbook_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('kyc_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False, server_default='not_started'),
    sa.Column('business_name', sa.String(length=300), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('business_address', sa.Text(), nullable=True),
    sa.Column('business_phone', sa.String(length=50), nullable=True),
    sa.Column('business_website', sa.String(length=500), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('personal_address', sa.Text(), nullable=True),
    sa.Column('government_id_type', sa.String(length=50), nullable=True),
    sa.Column('government_id_number', sa.String(length=100), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id']),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kyc_verifications')
    op.drop_table('smart_import_items')
    op.drop_table('smart_imports')
    op.drop_table('brain_chat_files')
    # ### end Alembic commands ###
