"""add proposals esign ghl followup tables

Revision ID: c72344904b2c
Revises: 81d2dd1adfb0
Create Date: 2026-03-06 00:21:06.935803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72344904b2c'
down_revision: Union[str, None] = '81d2dd1adfb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_resource_type'))

    with op.batch_alter_table('approval_workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_workflows_status'))

    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_notes_status'))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))

    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estimates_status'))

    with op.batch_alter_table('expense_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_approvals_status'))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_status'))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_contact_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_due_date'))
        batch_op.drop_index(batch_op.f('ix_invoices_issue_date'))
        batch_op.drop_index(batch_op.f('ix_invoices_status'))

    with op.batch_alter_table('meeting_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_recordings_status'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_recordings_status'), ['status'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_issue_date'), ['issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_contact_status'), ['contact_id', 'status'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_status'), ['status'], unique=False)

    with op.batch_alter_table('expense_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_approvals_status'), ['status'], unique=False)

    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estimates_status'), ['status'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_notes_status'), ['status'], unique=False)

    with op.batch_alter_table('approval_workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_workflows_status'), ['status'], unique=False)

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_resource_type'), ['resource_type'], unique=False)

    # ### end Alembic commands ###
