"""add document_id to income_entries

Revision ID: c7574fecfcf7
Revises: 6eb875a50e5d
Create Date: 2026-02-27 23:34:56.823299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7574fecfcf7'
down_revision: Union[str, None] = '6eb875a50e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_income_entries_document_id'), ['document_id'], unique=False)
        batch_op.create_foreign_key('fk_income_entries_document_id', 'documents', ['document_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_income_entries_document_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_income_entries_document_id'))
        batch_op.drop_column('document_id')

    # ### end Alembic commands ###
