"""add meetings office and drive enhancements

Revision ID: cfbf3dcffee1
Revises: c7574fecfcf7
Create Date: 2026-02-28 15:02:29.127251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cfbf3dcffee1'
down_revision: Union[str, None] = 'c7574fecfcf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.Enum('DOCUMENT', 'SPREADSHEET', 'PRESENTATION', name='doctype'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('yjs_state', sa.LargeBinary(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_json', sqlite.JSON(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('is_starred', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_trashed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('trashed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('office_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_office_documents_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_office_documents_folder_id'), ['folder_id'], unique=False)

    op.create_table('office_document_access',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.Enum('VIEW', 'COMMENT', 'EDIT', name='permission'), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['office_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'user_id', name='uq_office_doc_access')
    )
    with op.batch_alter_table('office_document_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_office_document_access_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_office_document_access_user_id'), ['user_id'], unique=False)

    op.create_table('meetings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='meetingstatus'), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('livekit_room_name', sa.String(length=100), nullable=False),
    sa.Column('record_meeting', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('calendar_event_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('livekit_room_name')
    )
    op.create_table('meeting_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('HOST', 'PARTICIPANT', name='participantrole'), nullable=False),
    sa.Column('join_token', sa.String(length=500), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('join_token')
    )
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_participants_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('meeting_recordings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('RECORDING', 'PROCESSING', 'AVAILABLE', 'FAILED', name='recordingstatus'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('egress_id', sa.String(length=100), nullable=True),
    sa.Column('started_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_recordings_meeting_id'), ['meeting_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_starred', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_trashed', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('trashed_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_starred', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_trashed', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_column('is_trashed')
        batch_op.drop_column('is_starred')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('trashed_at')
        batch_op.drop_column('is_trashed')
        batch_op.drop_column('is_starred')

    with op.batch_alter_table('meeting_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_recordings_meeting_id'))

    op.drop_table('meeting_recordings')
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_participants_meeting_id'))

    op.drop_table('meeting_participants')
    op.drop_table('meetings')
    with op.batch_alter_table('office_document_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_office_document_access_user_id'))
        batch_op.drop_index(batch_op.f('ix_office_document_access_document_id'))

    op.drop_table('office_document_access')
    with op.batch_alter_table('office_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_office_documents_folder_id'))
        batch_op.drop_index(batch_op.f('ix_office_documents_created_by'))

    op.drop_table('office_documents')
    # ### end Alembic commands ###
