"""page_builder_v2_domains_split_tests_logo

Revision ID: e1e481069afe
Revises: c9e1f2a3b4d5
Create Date: 2026-03-08 13:04:17.290091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e481069afe'
down_revision: Union[str, None] = 'c9e1f2a3b4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_domains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('website_id', sa.Uuid(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('domain_type', sa.String(length=20), nullable=False),
    sa.Column('dns_record_type', sa.String(length=10), nullable=False),
    sa.Column('dns_target', sa.String(length=255), nullable=True),
    sa.Column('dns_verified', sa.Boolean(), nullable=False),
    sa.Column('ssl_status', sa.String(length=20), nullable=False),
    sa.Column('ssl_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    with op.batch_alter_table('custom_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_domains_page_id'), ['page_id'], unique=False)

    op.create_table('split_tests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'PAUSED', 'COMPLETED', name='splitteststatus'), nullable=False),
    sa.Column('auto_optimize', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winner_variation_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('split_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_split_tests_page_id'), ['page_id'], unique=False)

    op.create_table('split_test_variations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('css_content', sa.Text(), nullable=True),
    sa.Column('traffic_percentage', sa.Integer(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['split_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('split_test_variations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_split_test_variations_test_id'), ['test_id'], unique=False)

    op.create_table('split_test_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('visitor_id', sa.String(length=64), nullable=False),
    sa.Column('variation_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['split_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variation_id'], ['split_test_variations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('split_test_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_split_test_assignments_test_id'), ['test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_split_test_assignments_visitor_id'), ['visitor_id'], unique=False)

    with op.batch_alter_table('branding_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_type', sa.String(length=20), server_default='text', nullable=False))
        batch_op.add_column(sa.Column('logo_text_settings_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('logo_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('logo_image_light_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('logo_image_dark_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('logo_mark_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('logo_max_height', sa.Integer(), server_default='40', nullable=False))
        batch_op.add_column(sa.Column('logo_layout', sa.String(length=20), server_default='horizontal', nullable=False))

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('live_html_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('live_css_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('auto_publish', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('next_page_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('page_purpose', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_pages_next_page', 'pages', ['next_page_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###




def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pages_next_page', type_='foreignkey')
        batch_op.drop_column('page_purpose')
        batch_op.drop_column('next_page_id')
        batch_op.drop_column('auto_publish')
        batch_op.drop_column('live_css_content')
        batch_op.drop_column('live_html_content')

    with op.batch_alter_table('branding_settings', schema=None) as batch_op:
        batch_op.drop_column('logo_layout')
        batch_op.drop_column('logo_max_height')
        batch_op.drop_column('logo_mark_url')
        batch_op.drop_column('logo_image_dark_url')
        batch_op.drop_column('logo_image_light_url')
        batch_op.drop_column('logo_image_url')
        batch_op.drop_column('logo_text_settings_json')
        batch_op.drop_column('logo_type')

    with op.batch_alter_table('split_test_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_split_test_assignments_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_split_test_assignments_test_id'))

    op.drop_table('split_test_assignments')
    with op.batch_alter_table('split_test_variations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_split_test_variations_test_id'))

    op.drop_table('split_test_variations')
    with op.batch_alter_table('split_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_split_tests_page_id'))

    op.drop_table('split_tests')
    with op.batch_alter_table('custom_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_domains_page_id'))

    op.drop_table('custom_domains')
    # ### end Alembic commands ###
