"""add phase3 workflows forms communication

Revision ID: eef17b52e8a1
Revises: 11af39e2af84
Create Date: 2026-03-06 11:58:13.321701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef17b52e8a1'
down_revision: Union[str, None] = '11af39e2af84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fields_json', sa.Text(), nullable=False),
    sa.Column('thank_you_type', sa.String(length=50), server_default='message', nullable=False),
    sa.Column('thank_you_config_json', sa.Text(), nullable=True),
    sa.Column('style_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twilio_phone_numbers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('assigned_user_id', sa.Uuid(), nullable=True),
    sa.Column('friendly_name', sa.String(length=255), nullable=True),
    sa.Column('capabilities_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('twilio_phone_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_twilio_phone_numbers_assigned_user_id'), ['assigned_user_id'], unique=False)

    op.create_table('workflows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.Enum('CONTACT_CREATED', 'CONTACT_TAG_ADDED', 'CONTACT_TAG_REMOVED', 'FORM_SUBMITTED', 'APPOINTMENT_BOOKED', 'APPOINTMENT_CANCELLED', 'APPOINTMENT_COMPLETED', 'INVOICE_CREATED', 'INVOICE_SENT', 'INVOICE_PAID', 'INVOICE_OVERDUE', 'PROPOSAL_SENT', 'PROPOSAL_VIEWED', 'PROPOSAL_SIGNED', 'PROPOSAL_DECLINED', 'PAYMENT_RECEIVED', 'PIPELINE_STAGE_CHANGED', 'CALL_COMPLETED', 'SMS_RECEIVED', 'EMAIL_OPENED', 'SCHEDULED', 'WEBHOOK_RECEIVED', name='triggertype'), nullable=False),
    sa.Column('trigger_config_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=False),
    sa.Column('to_number', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_logs_contact_id'), ['contact_id'], unique=False)

    op.create_table('form_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('form_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_submissions_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_submissions_form_id'), ['form_id'], unique=False)

    op.create_table('live_chat_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('visitor_name', sa.String(length=255), nullable=True),
    sa.Column('visitor_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('assigned_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_chat_sessions_contact_id'), ['contact_id'], unique=False)

    op.create_table('sms_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=False),
    sa.Column('to_number', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('twilio_sid', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_messages_contact_id'), ['contact_id'], unique=False)

    op.create_table('workflow_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'WAITING', 'CANCELLED', name='executionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_executions_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_executions_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('workflow_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('SEND_EMAIL', 'SEND_SMS', 'ADD_TAG', 'REMOVE_TAG', 'UPDATE_CONTACT_FIELD', 'CREATE_CONTACT', 'MOVE_PIPELINE_STAGE', 'CREATE_TASK', 'CREATE_NOTE', 'CREATE_INVOICE', 'SEND_PROPOSAL', 'WAIT_DELAY', 'IF_ELSE_BRANCH', 'WEBHOOK_OUTBOUND', 'ADD_TO_WORKFLOW', 'REMOVE_FROM_WORKFLOW', 'ASSIGN_TO_USER', 'SEND_NOTIFICATION', 'ASK_OBRAIN', 'LOG_TO_BRAIN', name='actiontype'), nullable=False),
    sa.Column('action_config_json', sa.Text(), nullable=True),
    sa.Column('condition_json', sa.Text(), nullable=True),
    sa.Column('wait_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_steps_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('live_chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['live_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('workflow_execution_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'WAITING', 'CANCELLED', name='executionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_execution_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_execution_steps_execution_id'), ['execution_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_execution_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_execution_steps_execution_id'))

    op.drop_table('workflow_execution_steps')
    with op.batch_alter_table('live_chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_chat_messages_session_id'))

    op.drop_table('live_chat_messages')
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_steps_workflow_id'))

    op.drop_table('workflow_steps')
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_executions_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_executions_contact_id'))

    op.drop_table('workflow_executions')
    with op.batch_alter_table('sms_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_messages_contact_id'))

    op.drop_table('sms_messages')
    with op.batch_alter_table('live_chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_chat_sessions_contact_id'))

    op.drop_table('live_chat_sessions')
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_submissions_form_id'))
        batch_op.drop_index(batch_op.f('ix_form_submissions_contact_id'))

    op.drop_table('form_submissions')
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_logs_contact_id'))

    op.drop_table('call_logs')
    op.drop_table('workflows')
    with op.batch_alter_table('twilio_phone_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twilio_phone_numbers_assigned_user_id'))

    op.drop_table('twilio_phone_numbers')
    op.drop_table('forms')
    # ### end Alembic commands ###
